### ISSUE TITLE
왜 클론 코딩을 선택하셨는지 궁금합니다.

### ISSUE THREAD

**Issue by swszz** [rachel-park-dev/caroot-market#1]
클론 코딩을 선택한 이유가 무엇인가요? 
기술 학습을 위한 클론 코딩인지? 아니면 다른 이유가 있는지 너무 궁금합니다.

p.s.
보라님께 자극을 받아 더 열심히 공부하고 있다는 사실을 전해드립니다.

**Comment by brparkk** [comment]
@swszz 기술 학습을 위한 목적이 가장 크다고 볼 수 있습니다. 
해당 프로젝트를 진행하면서 신규 기술을 학습하고 이를 실무에 적용할 계획입니다. (신규 프로젝트에 Next.js를 적용할 계획입니다.)
또한, 프론트엔드 개발 뿐 아니라 백엔드 개발도 구현하여서 전체적인 플로우의 이해, 아키텍쳐에 대한 고민들 또한 함께 해볼 수 있어서 선택하게 되었습니다.

p.s.
행복하신가요?

**Comment by swszz** [comment]
상당히 멋진 이유군요.
역시 멋진 동료라고 생각하고 있던 제 판단은 틀리지 않았던 거 같습니다.

저는 행복하고 즐겁게 지내고 있습니다.
최고의 복지는 동료라는 말을 피부로 느끼고 있습니다.
언젠가 주니어 프론트엔드 개발자 공고가 올라오면 보라님께 꼭 추천드리고 싶군요.

**Comment by brparkk** [comment]
최고의 복지는 동료라는 말 정말 멋진 말인거 같아요!
말만 들어도 얼마나 행복하게 보내고 계실지 짐작이 가네요.

그렇다면, 저는 추천을 기다리고 있겠습니다 후후🤭

p.s.
커피챗 신청하면 받아주시나요??
그곳의 개발 문화는 어떠한지, 다른 회사는 어떤 비전을 가지고 있는지 등이 궁금합니다.

**Comment by swszz** [comment]
빠른 시일 내에 공고가 나오길... 🙏🏻 
 
커피챗은 언제든 환영이죠!
일정만 알려주신다면 어디든 가겠습니다~~!

솔직한 의견을 모두 전달드릴게요 😄

**Comment by brparkk** [comment]
조만간 연락드릴게요~~! 🧸
